#!/bin/bash
cd graphDB &&
opam -y install dune &&
opam -y install . --deps-only &&
opam -y install core yojson menhir &&
opam -y install ppx_deriving &&
opam -y install ocamlgraph &&
opam -y switch create . 5.0.0 &&
eval $(opam env) &&
dune build &&
dune exec Proj_GraphDB